### post new user 
post http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_kaushik",
  "name": "kaushik",
  "password": "kaushik1234",
  "gender": "male",
  "location": "Detroit"
}

### post user login
post http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}


### put change-pass
put http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}